name: Run js actions

on:
  push:
    branches:
      - main

jobs:
  run-js-script:
    runs-on: ubuntu-latest
    steps:
      - name: checkout to branch
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: "24"
      - name: run-script
        uses: ./.github/actions/jsLogger
        with:
          message: "Custom message"
