name: Run js actions

on:
  push:
    branches:
      - main

jobs:
  show-env:
    runs-on: ubuntu-latest
    environment: Example Environment
    steps:
      - name: Print Github Env
        run: echo "${{ toJson(github.env) }}"
  run-js-script:
    runs-on: ubuntu-latest
    steps:
      - name: Print Github Env
        run: echo "${{ toJson(github.env) }}"
      - name: Print Env
        run: echo "${{ toJson(env) }}"
      - name: Print Secrets
        run: echo "${{ toJson(secrets) }}"
      - name: Print Secrets
        run: echo "${{ toJson(env) }}"
      - name: checkout to branch
        uses: actions/checkout@v4
      - name: run-script
        uses: ./.github/actions/jsLogger
        with:
          message: "Custom message"
